### ISSUE TITLE
how to delete the hole?

### ISSUE THREAD

**Issue by stphtan94117** [vietanhdev/anylabeling#3]
for example, I want to label donuts, but need to erase holes.
i do not know how to delete this hole.
this image is same as donut case, how to label?

![image](https://user-images.githubusercontent.com/110151053/231433635-7ced797b-75cf-47e7-b5ab-211afb4d459f.png)
![image](https://user-images.githubusercontent.com/110151053/231433659-64572bcc-3087-4f72-b5a3-abe8bac8a577.png)
i want to get 2nd image result, but i do not have any idea.
(i use labelme and labelme cant delete middle hole)

**Comment by vietanhdev** [comment]
In this case you need a tool for brush labeling.
Please check Label Studio - Brush segmentation. https://labelstud.io/playground/
AnyLabeling may support this in the future, but not very soon.

**Comment by ryouchinsa** [comment]
[RectLabel](https://rectlabel.com) is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can label pixels using the polygon brush tool and export to the COCO RLE format or the mask PNG file.

![diamond_with_hole](https://github.com/vietanhdev/anylabeling/assets/1954306/6281fdae-f2ac-48d0-b94f-8b7b15e82566)

**Comment by ryouchinsa** [comment]
Improved "Create polygon using SAM" feature so that you can label pixels using the pixels option. You can label [Segment Anything 1 Billion (SA-1B)](https://ai.meta.com/datasets/segment-anything-downloads/) like dataset by yourself.

![sam-pixels](https://github.com/facebookresearch/segment-anything/assets/1954306/d828c18b-6fda-4258-b866-21bc34a0d17f)
